export const hVsHName = "Human vs Human"; // TODO: saa lahti
export const hVsAiName = "Human vs AI"; // TODO: saa lahti
export const xPiece = "X"; // TODO: saa lahti
export const oPiece = "O"; // TODO: saa lahti
export const spacerPiece = "S"; // TODO: saa lahti

export const mainHeading = "Tic-Tac-Two";
export const gameOverHeading = "GAME OVER";
export const chooseGameModeText = "Choose game mode to start playing";
export const humansTurnText = ": Human, make your move.";
export const aisTurnText = "O: AI is thinking...";
export const resetButtonText = "Reset Game";
export const rulesHeadingText = "RULES";
export const rulesIntroText = "The game is similar to tic-tac-toe, but has a few modifications. Each player has 4 pieces. X starts. Play with a friend or against AI.";
export const turnHeadingText = "TURN";
export const turnOptionsAdditionalText = "After both players have placed 2 pieces, additional move options become available:";
export const turnOptionsText1 = "1. Player places a piece on the board.";
export const turnOptionsText2 = "2. Player can move their existing piece to another spot on the board (click on the piece you want to move + click on the new spot).";
export const turnOptionsText3 = "3. Player can move the grid one spot in any direction on the game board (use arrow keys + press enter to lock new position).";
export const winningHeadingText = "WINNING";
export const winningInfoText = "The goal is to get 3 pieces in a row inside the grid! The player who achieves this first, wins.";
export const footerText = "&copy; 2025 @annilember. All rights reserved.";
